Added contract for login and token validation
tavisca-cpadole/tavisca-exchange-authentication pull request #1
Opened 2019-10-17 12:37 UTC by tavisca-cpadole

2019-10-18 06:32 UTC, Tavisca-smohite requested changes

2019-10-18 06:32 UTC, Tavisca-smohite commented on Contracts/TokenAuth Api/error-response.json
> +    //Mandatory UnAuthorized Token Response
just keep it code and message

2019-10-18 06:32 UTC, Tavisca-smohite commented on Contracts/TokenAuth Api/request.json
> +//GET /api/tokenauth
is this call validates token or gets the token against auth key .?
what is the use case of this api

2019-10-18 06:32 UTC, Tavisca-smohite commented on Contracts/login/error-response.json5
> +{
error responses should be consistent for your all apis
````c#
{
"code" : 567,
"message" : "invalid token received in the request.",
"info" : [
{
"code" : "123",
"message" : "auth validation failed".
}
]
}
````

2019-10-18 06:32 UTC, Tavisca-smohite commented on Contracts/login/error-response.json5
> +{
or you can return list of errors if that is the use case of your api

2019-10-18 06:32 UTC, Tavisca-smohite commented on Contracts/login/request.json5
> +//POST /api/v1.0/Signin
keep names of urls consistent

2019-10-18 07:13 UTC, Tavisca-smohite commented on Contracts/TokenAuth Api/request.json
> +    "AuthKey": "adba-sd123.244_gss34"
1. update the name of url
2. make the parameter names consistent (headers are not exposed as json)

2019-10-18 07:14 UTC, Tavisca-smohite commented on Contracts/TokenAuth Api/response.json
> +    "Message":[
if in case of valid response , api consumer has no use of this field. Please do not pass redundant info in api response.

2019-10-18 09:38 UTC, Tavisca-smohite approved these changes

2019-10-18 10:54 UTC, achirametavisca requested changes

2019-10-18 10:54 UTC, achirametavisca commented on Contracts/Validate Access Token/error-response.json
> +//Error Response Data with 400:bad req/ 401: UnAuthorized
change file extension to json5 to remove red background around comment

2019-10-18 10:54 UTC, achirametavisca commented on Contracts/login/request.json5
> +	"rememberMe" : false
why rememberMe is required in API.
Lets discuss about this

2019-10-18 10:54 UTC, achirametavisca commented on Contracts/login/response.json5
> +	"refreshToken": 7992*&%^**********************,
why rememberMe/refreshToken is required in API.
Lets discuss about this

2019-10-18 10:54 UTC, achirametavisca commented on Contracts/Validate Access Token/request.json
> +#Header  "accessToken": "adba-sd123.244_gss34"
As per the last discussion we are validating access Token against user id

2019-10-22 08:30 UTC, achirametavisca approved these changes

2019-10-22 08:40 UTC, merged