Added user table implementation
tavisca-cpadole/tavisca-exchange-authentication pull request #5
Opened 2019-11-13 04:13 UTC by tavisca-cpadole

2019-11-13 04:38 UTC, Tavisca-smohite requested changes

2019-11-13 04:38 UTC, Tavisca-smohite commented on src/AuthenticationPortal.Contracts/Models/AddUserRequest.cs
> +        public string UserId { get; set; }
I believe userId should be part of response

2019-11-13 04:38 UTC, Tavisca-smohite commented on src/AuthenticationPortal.AwsExtension/AwsCognito.cs
> +                var response = await UserDetails.SaveAsync(addUserRequest, _userStore);
this should be handled in service layer, awscongnito's responsibility is to sign in the user and return the details

2019-11-14 15:36 UTC, achirametavisca approved these changes

2019-11-14 15:41 UTC, achirametavisca commented
Please merge

2019-11-14 15:45 UTC, merged